language: php
#
#branches:
#    only: master

matrix:
  fast_finish: true
  include:
    - php: 7.2

install:
    - phpenv config-rm xdebug.ini || echo 'xdebug not available'
    - phpenv config-add docker/php/config/php.ini
    - composer install --classmap-authoritative

script:
    - bin/benchmark --iteration 10
    - bin/benchmark --horizontal-complexity 30 --iteration 10
    - bin/benchmark --vertical-complexity 30 --iteration 10
    - bin/benchmark --horizontal-complexity 30 --vertical-complexity 30 --iteration 10
